### PR TITLE
add ruby enumerable method

### PR DESCRIPTION
**Pull request by jabichris**
This is the ruby implementation of the enumerable method.

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Christian, great job so far :+1: !
### Here are the changes you need to make before this project can be approved:
* [x] Pull Request should have meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
* [x] Project should have working `multiply_els` that uses `my_inject` as described on Odin ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/multiply_els.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
* [x] `my_inject` is not working. For test case `[5, 1, 2].my_inject("+") ` output is an error `private method 'my_inject' called for [5, 1, 2]:Array (NoMethodError)`, that should be fixed.
* [x] `my_any?` -  when a Regex is passed as an argument should return false if none of the collection matches the Regex:
` ['dog', 'door', 'rod', 'blade'].my_any?(/d/)` - should return true

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Good job @jabichris :+1:. A few cases are still not okay yet :fast_forward:**

1. **my_any?**
- When a class is passed, it should return true if at least one of the elements belong to that class.
`[1, "a", "b", "c"].my_any?(Integer)` should return `true`.
- It should accept patterns other than Classes and Regex, e.g a string "box".
`[1, "a", "box"].my_any?("box")' should return true since there is at least one element in the collection that matches the pattern "box". Right now, your method returns an error instead.


2. Your my_each method (used in my_inject) is throwing an error when your my_inject method is called on **a range**. Check it and try to fix it.

3. Check your spelling of enumerables in your README.

_**Kindly make these changes and submit another code review request.**_

**Any question? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

**Review by MauricioRobayo — CHANGES_REQUESTED** [review]
Very nice project!

It looks great and is coming into place, but we need to fix some issues before continuing:

#### `my_any?`

* [x] returns true if the block ever returns a value other than false or nil
```ruby
>> [1].any? { |n| n == 1 }
=> true
>> [1].my_any? { |n| n == 1 } # SystemStackError (stack level too deep)
```
* [x] when a class is passed as an argument returns true if at least one of the collection is a member of such class
```ruby
>> [1].any?(String)
=> false
>> [1].my_any?(String)
=> true
```

* [x] when a Regex is passed as an argument returns false if none of the collection matches the Regex
```ruby
>> %w[a b].any?(/\d/)
=> false
>> %w[a b].my_any?(/\d/)
=> true
```

* [x] when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern

```ruby
>> [1].any?(2)
=> false
>> [1].my_any?(2)
=> true
```

---

Optional:

* In the [Odin project #12](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2) you were asked to modify your `my_map` method to take either a proc or a block. And if both a proc and a block are given, only execute the proc. The real map doesn't have this feature.

```ruby
>> my_proc = Proc.new { |num| num > 5 }
>> [4, 6].my_map(my_proc) # should return false true
>> [4, 6].my_map(my_proc) { |num| num < 5 } # should return false true
```

* You could remove all debugging/testing from the source code and place it on the README.md or a different file as tests/examples. This helps to separate logic form user interface, also makes it easier to work with without unnecessary noise from debugging/test cases.

* Your filename is enum**a**rables.rb, I think you meant enum**e**rables.rb.

Status: __Request changes__.

**Comment by jabichris** [comment]
@MauricioRobayo, I worked on the feedback and I am submitting for a review

**Review by MauricioRobayo — CHANGES_REQUESTED** [review]
Almost there! Still some issues remaining on `my_any?`:

* [x] returns true if the block ever returns a value other than false or nil
```ruby
>> [1].any? { |n| n == 2 }
=> false
>> [1].my_any? { |n| n == 2 }
=> true
```
* [x] when no block or argument is given returns true if at least one of the collection is not false or nil
```ruby
>> [1].any?
=> true
>> [1].my_any?
=> false
```

* [x] when a class is passed as an argument returns true if at least one of the collection is a member of such class
```ruby
>> [1].any?(Integer)
=> true
>> [1].my_any?(Integer)
=> false
```

* [x] when a Regex is passed as an argument returns false if none of the collection matches the Regex
```ruby
>> %w[a b].my_any?(/\w/)
=> false
>> %w[a b].any?(/\w/)
=> true
```

* [x] when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
```ruby
>> [1].any?(1)
=> true
>> [1].my_any?(1)
=> false
```

Status: __Request changes__.

**Comment by jabichris** [comment]
@MauricioRobayo all fixed

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to develop.
_Goodluck in your next project_ *Happy coding*

**Comment by jabichris** [comment]
Nice! Let me proceed

**Pull request merged**
